export const Users = [
    {
        id:1,
        firstname: 'Firdaus',
        lastname: 'Juanda',
        companyId: 1,
        deptId:2,
        specialist: 'Programmer',
        profilePic: '1.jpeg',
    },
    {
        id:2,
        firstname: 'Ivan',
        lastname: 'Octanovianes',
        companyId: 1,
        deptId:1,
        specialist: 'Operator',
        profilePic: '2.jpeg',
    },
    {
        id:3,
        firstname: 'Feby',
        lastname: 'Clara',
        companyId: 2,
        deptId:1,
        specialist: 'Safety Officer',
        profilePic: '3.jpeg',
    },
    {
        id:4,
        firstname: 'Ade',
        lastname: 'Nisrina',
        companyId: 3,
        deptId:3,
        specialist: 'Admin',
        profilePic: '4.jpeg',
    },
    {
        id:5,
        firstname: 'Dedi',
        lastname: 'Kurniawan',
        companyId: 3,
        deptId:1,
        specialist: 'Civil',
        profilePic: '5.jpeg',
    },
    {
        id:6,
        firstname: 'Nofriadi',
        lastname: 'Sikumbang',
        companyId: 1,
        deptId:2,
        specialist: 'Electrical',
        profilePic: '6.jpeg',
    },
    {
        id:7,
        firstname: 'Rafiola',
        lastname: 'Fitri',
        companyId: 1,
        deptId:5,
        specialist: '',
        profilePic: '7.jpeg',
    },
];

export const Posts = [
    {
        id:1,
        userId:1,
        vCompanyId:2,
        img: 'p1.jpeg',
        date:'10 mins ago',
        title: 'Perbaikan gudang kontainer', 
        companyId: 1,
        color:'#ea31fa',
        deptId: 2,
        desc: 'Perbaikan kontainer dilakukan dengan mengganti atap kontainer, memasang plafon, dan pengganti pintu kontainer',
        createdAt: '5mins ago',
    },
    {
        id:2,
        userId:1,
        vCompanyId:2,
        img: 'p2.jpeg',
        date:'1 day ago',
        title: 'Penggantian atap seng store', 
        companyId: 1,
        color:'#ea31fa',
        deptId: 3,
        desc: 'Atap difabrikasi dan dipasang dibagian utara store',
        createdAt: '5mins ago',
    },
    {
        id:3,
        userId:2,
        vCompanyId:2,
        companyId: 1,
        deptId: 1,
        color:'#ea31fa',
        date:'4 mins ago',
        img: 'p3.jpeg',
        title: 'Perbaikan gudang kontainer', 
        desc: 'Perbaikan kontainer dilakukan dengan mengganti atap kontainer, memasang plafon, dan pengganti pintu kontainer',
        createdAt: '5mins ago',
    },
    {
        id:4,
        userId:1,
        vCompanyId:2,
        companyId: 1,
        deptId: 2,
        color:'#ea31fa',
        date:'3 hours ago',
        img: 'p4.jpeg',
        title: 'Perbaikan gudang kontainer', 
        desc: 'Perbaikan kontainer dilakukan dengan mengganti atap kontainer, memasang plafon, dan pengganti pintu kontainer',
        createdAt: '5mins ago',
    },
    {
        id:5,
        userId:1,
        vCompanyId:2,
        companyId: 1,
        deptId: 2,
        color:'#ea31fa',
        date:'8 days ago',
        img: 'p5.jpeg',
        title: 'Perbaikan gudang kontainer', 
        desc: 'Perbaikan kontainer dilakukan dengan mengganti atap kontainer, memasang plafon, dan pengganti pintu kontainer',
        createdAt: '5mins ago',
    },
    {
        id:6,
        userId:1,
        vCompanyId:2,
        companyId: 1,
        deptId: 5,
        color:'#ea31fa',
        date:'2 mins ago',
        img: 'p6.jpeg',
        title: 'Perbaikan gudang kontainer', 
        desc: 'Perbaikan kontainer dilakukan dengan mengganti atap kontainer, memasang plafon, dan pengganti pintu kontainer',
        createdAt: '5mins ago',
    },
    {
        id:7,
        userId:1,
        vCompanyId:2,
        companyId: 1,
        deptId: 2,
        color:'#ea31fa',
        date:'10 hour ago',
        img: 'p7.jpeg',
        title: 'Perbaikan gudang kontainer', 
        desc: 'Perbaikan kontainer dilakukan dengan mengganti atap kontainer, memasang plafon, dan pengganti pintu kontainer',
        createdAt: '5mins ago',
    },
]